version: '3.8'

services:
  wills-notes:
    image: ghcr.io/willnekker/wills-notes:latest
    ports:
      - "80:80"
    volumes:
      - wills-notes-data:/app/data
      - wills-notes-uploads:/app/uploads
    environment:
      - JWT_SECRET=change-this-to-a-secure-random-string-in-production
      - PORT=3000
      - NODE_ENV=production
      - DB_SOURCE=data/notes.db
      - UPLOAD_DIR=./uploads
      - MAX_FILE_SIZE=10485760
      - WEATHER_API_KEY=your_weather_api_key_here
      - OPENROUTER_API_KEY=your_openrouter_api_key_here
    restart: unless-stopped

volumes:
  wills-notes-data:
  wills-notes-uploads: